import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Sidebar1 from "@/components/Sidebar1";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function userLayout({ children }) {
  return (
   
        <div className="p-5 bg-custom-dark">

        <div className="flex border-[1px] border-[rgba(255,255,255,0.1)] rounded-sm ">

          <Sidebar1/>

        <Sidebar/>
        {children}
        </div>
        </div>
        
       
  );
}
